use std::path::{Path, PathBuf};

pub fn rom_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../pokeyellow.gbc")
}

pub fn sym_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../pokeyellow.sym")
}

pub fn load_rom_bytes(path: &str) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|e| panic!("Failed to read ROM file {path}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rom_path_ends_with_gbc() {
        let p = rom_path();
        assert_eq!(p.extension().and_then(|e| e.to_str()), Some("gbc"));
    }

    #[test]
    fn sym_path_ends_with_sym() {
        let p = sym_path();
        assert_eq!(p.extension().and_then(|e| e.to_str()), Some("sym"));
    }

    #[test]
    fn rom_file_exists() {
        let p = rom_path();
        if p.exists() {
            let bytes = load_rom_bytes(p.to_str().unwrap());
            assert!(!bytes.is_empty(), "ROM file should not be empty");
        }
    }

    #[test]
    fn sym_file_exists() {
        let p = sym_path();
        if p.exists() {
            let content = std::fs::read_to_string(&p).unwrap();
            assert!(
                content.contains("; File generated by rgblink"),
                "sym file should have rgblink header"
            );
        }
    }
}
