use std::collections::HashMap;
use std::fs;

pub struct SymbolTable {
    symbols: HashMap<String, (u8, u16)>,
}

impl SymbolTable {
    pub fn load(path: &str) -> Self {
        let content = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Failed to read symbol file {path}: {e}"));
        Self::parse(&content)
    }

    fn parse(content: &str) -> Self {
        let mut symbols = HashMap::new();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with(';') {
                continue;
            }
            // Format: BB:AAAA LabelName
            let Some((addr_part, label)) = line.split_once(' ') else {
                continue;
            };
            let Some((bank_str, addr_str)) = addr_part.split_once(':') else {
                continue;
            };
            let Ok(bank) = u8::from_str_radix(bank_str, 16) else {
                continue;
            };
            let Ok(addr) = u16::from_str_radix(addr_str, 16) else {
                continue;
            };
            symbols.insert(label.to_string(), (bank, addr));
        }
        SymbolTable { symbols }
    }

    pub fn resolve(&self, label: &str) -> Option<(u8, u16)> {
        self.symbols.get(label).copied()
    }

    pub fn rom_offset(&self, label: &str) -> Option<usize> {
        let (bank, addr) = self.resolve(label)?;
        if bank == 0 {
            Some(addr as usize)
        } else {
            Some(bank as usize * 0x4000 + (addr as usize - 0x4000))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_SYM: &str = "\
; File generated by rgblink
00:0000 NULL
00:0061 DisableLCD
00:006b DisableLCD.wait
01:4ae6 Gym_Coll
0f:6700 MoveHitTest
0f:6764 MoveHitTest.enemyTurn
";

    #[test]
    fn parse_bank_zero() {
        let table = SymbolTable::parse(TEST_SYM);
        assert_eq!(table.resolve("DisableLCD"), Some((0x00, 0x0061)));
    }

    #[test]
    fn parse_local_label() {
        let table = SymbolTable::parse(TEST_SYM);
        assert_eq!(table.resolve("DisableLCD.wait"), Some((0x00, 0x006b)));
    }

    #[test]
    fn parse_nonzero_bank() {
        let table = SymbolTable::parse(TEST_SYM);
        assert_eq!(table.resolve("Gym_Coll"), Some((0x01, 0x4ae6)));
        assert_eq!(table.resolve("MoveHitTest"), Some((0x0f, 0x6700)));
    }

    #[test]
    fn resolve_missing_returns_none() {
        let table = SymbolTable::parse(TEST_SYM);
        assert_eq!(table.resolve("NonExistent"), None);
    }

    #[test]
    fn rom_offset_bank_zero() {
        let table = SymbolTable::parse(TEST_SYM);
        // Bank 0, addr 0x0061 -> offset 0x0061
        assert_eq!(table.rom_offset("DisableLCD"), Some(0x0061));
    }

    #[test]
    fn rom_offset_bank_one() {
        let table = SymbolTable::parse(TEST_SYM);
        // Bank 1, addr 0x4ae6 -> 1 * 0x4000 + (0x4ae6 - 0x4000) = 0x4ae6
        assert_eq!(table.rom_offset("Gym_Coll"), Some(0x4ae6));
    }

    #[test]
    fn rom_offset_bank_fifteen() {
        let table = SymbolTable::parse(TEST_SYM);
        // Bank 0x0f, addr 0x6700 -> 15 * 0x4000 + (0x6700 - 0x4000) = 0x3C000 + 0x2700 = 0x3E700
        assert_eq!(table.rom_offset("MoveHitTest"), Some(0x3E700));
    }

    #[test]
    fn rom_offset_missing_returns_none() {
        let table = SymbolTable::parse(TEST_SYM);
        assert_eq!(table.rom_offset("NonExistent"), None);
    }

    #[test]
    fn skips_comments_and_empty_lines() {
        let input = "; comment\n\n00:0010 Foo\n; another comment\n";
        let table = SymbolTable::parse(input);
        assert_eq!(table.resolve("Foo"), Some((0x00, 0x0010)));
        assert_eq!(table.symbols.len(), 1);
    }
}
